# Generated by Django 2.1.5 on 2019-01-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='todo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
